config/routes.rb
Rails.application.routes.draw do
  resources :dealerships

  resources :inventories

  resources :finances

  resources :sales

  root 'sales#index'

end

app/models/dealership.rb
class Dealership < ActiveRecord::Base

  belongs_to: finance

end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  before_action :set_dealership, only: [:show, :edit, :update, :destroy]

  # GET /dealerships
  # GET /dealerships.json
  def index
    @dealerships = Dealership.all
  end

  # GET /dealerships/1
  # GET /dealerships/1.json
  def show
  end

  # GET /dealerships/new
  def new
    @dealership = Dealership.new
  end

  # GET /dealerships/1/edit
  def edit
  end

  # POST /dealerships
  # POST /dealerships.json
  def create
    @dealership = Dealership.new(dealership_params)

    respond_to do |format|
      if @dealership.save
        format.html { redirect_to @dealership, notice: 'Dealership was successfully created.' }
        format.json { render :show, status: :created, location: @dealership }
      else
        format.html { render :new }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealerships/1
  # PATCH/PUT /dealerships/1.json
  def update
    respond_to do |format|
      if @dealership.update(dealership_params)
        format.html { redirect_to @dealership, notice: 'Dealership was successfully updated.' }
        format.json { render :show, status: :ok, location: @dealership }
      else
        format.html { render :edit }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealerships/1
  # DELETE /dealerships/1.json
  def destroy
    @dealership.destroy
    respond_to do |format|
      format.html { redirect_to dealerships_url, notice: 'Dealership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealership
      @dealership = Dealership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dealership_params
      params.require(:dealership).permit(:total_gross_revenue, :net_profit, :sales_tax_totals)
    end
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/views/dealerships/_form.html.erb
<%= form_for(@dealership) do |f| %>
  <% if @dealership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dealership.errors.count, "error") %> prohibited this dealership from being saved:</h2>

      <ul>
      <% @dealership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total_gross_revenue %><br>
    <%= f.number_field :total_gross_revenue %>
  </div>
  <div class="field">
    <%= f.label :net_profit %><br>
    <%= f.number_field :net_profit %>
  </div>
  <div class="field">
    <%= f.label :sales_tax_totals %><br>
    <%= f.number_field :sales_tax_totals %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dealerships/edit.html.erb
<h1>Editing Dealership</h1>

<%= render 'form' %>

<%= link_to 'Show', @dealership %> |
<%= link_to 'Back', dealerships_path %>

app/views/dealerships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dealerships</h1>

<table>
  <thead>
    <tr>
      <th>Total gross revenue</th>
      <th>Net profit</th>
      <th>Sales tax totals</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dealerships.each do |dealership| %>
      <tr>
        <td><%= dealership.total_gross_revenue %></td>
        <td><%= dealership.net_profit %></td>
        <td><%= dealership.sales_tax_totals %></td>
        <td><%= link_to 'Show', dealership %></td>
        <td><%= link_to 'Edit', edit_dealership_path(dealership) %></td>
        <td><%= link_to 'Destroy', dealership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dealership', new_dealership_path %>

app/views/dealerships/new.html.erb
<h1>New Dealership</h1>

<%= render 'form' %>

<%= link_to 'Back', dealerships_path %>

app/views/dealerships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total gross revenue:</strong>
  <%= @dealership.total_gross_revenue %>
</p>

<p>
  <strong>Net profit:</strong>
  <%= @dealership.net_profit %>
</p>

<p>
  <strong>Sales tax totals:</strong>
  <%= @dealership.sales_tax_totals %>
</p>

<%= link_to 'Edit', edit_dealership_path(@dealership) %> |
<%= link_to 'Back', dealerships_path %>