config/routes.rb
Rails.application.routes.draw do
  resources :dealerships

  resources :inventories

  resources :finances

  resources :sales

  root 'sales#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base

  belongs_to: inventory
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:sales_id, :salesperson, :customer, :quote, :year, :model, :color, :vin, :status)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :salesperson %><br>
    <%= f.select(:salesperson, ['Aakas Desai', 'Peter Griffin', 'Stewie Griffin', 'Keith Lancaster', 'Kobe Bryant'], {}, {:class => 'Salesperson'}) %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :quote %><br>
    <%= f.number_field :quote %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="Status">
    <%= f.label :status %><br>
    <%= f.select(:status, ['Available', 'Pending', 'Sold'], {}, {:class => 'status'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Salesperson</th>
      <th>Customer</th>
      <th>Quote</th>
      <th>Year</th>
      <th>Model</th>
      <th>Color</th>
      <th>VIN</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.salesperson %></td>
        <td><%= sale.customer %></td>
        <td><%= sale.quote %></td>
        <td><%= sale.year %></td>
        <td><%= sale.model %></td>
        <td><%= sale.color %></td>
        <td><%= sale.vin %></td>
        <td><%= sale.status %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sales:</strong>
  <%= @sale.sales_id %>
</p>

<p>
  <strong>Salesperson:</strong>
  <%= @sale.salesperson %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer %>
</p>

<p>
  <strong>Quote:</strong>
  <%= @sale.quote %>
</p>

<p>
  <strong>Year:</strong>
  <%= @sale.year %>
</p>

<p>
  <strong>Model:</strong>
  <%= @sale.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @sale.color %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @sale.vin %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sale.status %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>